### PR TITLE
Remove (debug) print statement

### PR DESCRIPTION
**Pull request by sergei-maertens**

### CODE REVIEW

**Comment by jrobichaud** [comment]
This should be merged.

**Comment by sergei-maertens** [comment]
@gradam do you need help getting this released? Anything we can do? :slightly_smiling_face:

**Comment by dmartin** [comment]
2fd03e412f75e182b5d6b169f5279a65a28e6203 also introduced a second print statement into `forms/fields.py` (not yet captured in this PR): 

https://github.com/gradam/django-better-admin-arrayfield/blob/2fd03e412f75e182b5d6b169f5279a65a28e6203/django_better_admin_arrayfield/forms/fields.py#L25

**Comment by sergei-maertens** [comment]
@dmartin I've updated my PR to remove that one too :)

**Pull request merged**
